import type { ScanResult, Finding, Severity, ScannerName } from "../types.js";
import { SCANNER_DISPLAY_NAMES } from "../types.js";

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: "\u{1F534}",
  high: "\u{1F7E0}",
  medium: "\u{1F7E1}",
  low: "\u{1F7E2}",
  info: "\u{2139}\u{FE0F}",
  pass: "\u2705",
};

export function formatMarkdown(result: ScanResult): string {
  const lines: string[] = [];

  lines.push("# \u{1F6E1}\u{FE0F} MCP Shield Security Report");
  lines.push("");
  lines.push(`**Target:** ${result.target}${result.version ? ` v${result.version}` : ""}`);
  lines.push(`**Date:** ${new Date(result.timestamp).toLocaleDateString()}`);
  lines.push(`**Score:** ${result.score}/100 (${result.passed ? "PASS" : "FAIL"})`);
  lines.push("");

  // Summary table
  lines.push("## Summary");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  if (result.summary.critical > 0) lines.push(`| \u{1F534} Critical | ${result.summary.critical} |`);
  if (result.summary.high > 0) lines.push(`| \u{1F7E0} High | ${result.summary.high} |`);
  if (result.summary.medium > 0) lines.push(`| \u{1F7E1} Medium | ${result.summary.medium} |`);
  if (result.summary.low > 0) lines.push(`| \u{1F7E2} Low | ${result.summary.low} |`);
  if (result.summary.pass > 0) lines.push(`| \u2705 Pass | ${result.summary.pass} |`);
  lines.push("");

  // Group findings by scanner
  const grouped = groupByScanner(result.findings);

  lines.push("## Findings");
  lines.push("");

  for (const [scanner, findings] of grouped) {
    lines.push(`### ${formatScannerName(scanner)}`);
    lines.push("");

    for (const finding of findings) {
      lines.push(formatFinding(finding));
    }
    lines.push("");
  }

  // Errors
  if (result.errors.length > 0) {
    lines.push("## Scanner Errors");
    lines.push("");
    for (const error of result.errors) {
      lines.push(`- **${error.scanner}**: ${error.message}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [mcp-shield](https://github.com/BuildWithAbid/mcp-shield)*");

  return lines.join("\n");
}

function formatFinding(finding: Finding): string {
  const emoji = SEVERITY_EMOJI[finding.severity];
  const severity = finding.severity.toUpperCase();
  let line = `- ${emoji} **${severity}** — ${finding.title}`;

  if (finding.description) {
    line += `\n  ${finding.description}`;
  }

  if (finding.file) {
    line += `\n  *File: \`${finding.file}${finding.line ? `:${finding.line}` : ""}\`*`;
  }

  if (finding.remediation) {
    line += `\n  > **Fix:** ${finding.remediation}`;
  }

  return line;
}

function groupByScanner(findings: Finding[]): Map<string, Finding[]> {
  const map = new Map<string, Finding[]>();
  for (const f of findings) {
    const existing = map.get(f.scanner) ?? [];
    existing.push(f);
    map.set(f.scanner, existing);
  }
  return map;
}

function formatScannerName(name: string): string {
  return SCANNER_DISPLAY_NAMES[name as ScannerName]?.long ?? name;
}
